-d D:\work\gowin\projects\riscv_soc\riscv_soc\impl\gwsynthesis\riscv_soc.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst D:\work\gowin\projects\riscv_soc\riscv_soc\src\riscv_soc.cst
-cfg D:\work\gowin\projects\riscv_soc\riscv_soc\impl\pnr\device.cfg
-sdc D:\work\gowin\projects\riscv_soc\riscv_soc\src\riscv_soc.sdc
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
