-d E:\FPGA\example\fpga_project\impl\gwsynthesis\fpga_project.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst E:\FPGA\example\fpga_project\src\fpga_project.cst
-cfg E:\FPGA\example\fpga_project\impl\pnr\device.cfg
-sdc E:\FPGA\example\fpga_project\src\fpga_project.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
